# Exercise 01 Practices of Python Language

In this exercise, you need to follow the requirements of each question to generate the Python code, and the following example is for reference：

- Sample Question: Write a program that takes the user's name as input and prints "Hello, [name]!" where [name] is the user's input.

- Potential Answer:

```python
    name = input("Enter your name: ")
    print("Hello, " + name + "!")
```
- If you enter 'David', the code will output 'Hello, David!', and this will satisfy the requirements.

## Attention
- Generally, there will be multiple answers for one question and you don't have to strictly follow the instructions in the tutorial, as long as you can make the output of the code meet the requirements of the question.
- If possible, strive to make your code concise and avoid excessive reliance on less commonly used libraries.
- You may need to search for information on the Internet to complete the excercise.

### Question 01: Write a program to calculate the area of a circle. Prompt the user to input the radius, and the program should output the area. Use the formula: Area = π * radius^2, where π is approximately 3.14.

### Write your answer in the following code frame:

In [5]:
import math
r = float(input("input the radius"))
area = math.pi * r**2
print(area)

3.141592653589793


### Question 02: Write a program that checks whether a given number is odd or even. Take an integer input from the user and output whether the number is odd or even.

### Write your answer in the following code frame:

In [1]:
num = int(input('write a number'))
if num % 2 == 1: 
    print('Odd')
else:
    print('Even')
exit()

Odd


: 

### Question 03: Write a program that finds the maximum and minimum values in a list and output them. The list should be generated by:

```python
    List = [3, 6, 1, -4, 8, 0, 9, 8, -2, 15]
```

### Write your answer in the following code frame:

In [1]:
List = [3, 6, 1, -4, 8, 0, 9, 8, -2, 15]
maximum = max(List)
minimum = min(List)
print(f"the max is {maximum}, the min is {minimum}")

the max is 15, the min is -4


### Question 04: Write a program that prints the first N (N>=2) numbers of the Fibonacci sequence. The Fibonacci sequence starts with 1 and 1, and each subsequent number is the sum of the two preceding ones like the following sequence:

```python
    1, 1, 2, 3, 5, 8, 13, ...
```

- If the input N is 5, you should print the result: 1, 2, 2, 3, 5.
- Your program should be able to output the result of any positive integer N.

### Write your answer in the following code frame:

In [6]:
def fib(num1, num2):
    output = int(num1+num2)
    return output

N = int(input("value of N is..."))
fib_seq = [1,1]
for _ in range(N-2):
    fib_seq.append(fib(fib_seq[-1], fib_seq[-2]))
print(fib_seq)
    



[1, 1]


### Question 05: Define a function that calculates the factorial of a given non-negative integer. The factorial is defined as: 
$$n! = n * (n-1) * (n-2) * ... * 1$$

- Hint: You can choose to use recursive methods to define (not neccessary)
  
### Write your answer in the following code frame:


In [9]:
def factorial(num: int):
    if num == 1: 
        return num 
    return num * factorial(num-1)
N = int(input('what is the value of n'))
output = factorial(N)
print(output)

720


### Question 06: Reshape the given numpy array (use the following code to generate) into a 2x5 matrix. Then, calculate the sum of each row and each column in the matrix and output them.
  
```python
    import numpy as np
    array = np.arange(1, 11)
```

### Write your answer in the following code frame:


In [13]:
import numpy as np
array = np.arange(1,11)
output = np.matrix([array[:-5],array[-5:]])
print(output)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Question 07: The following code can generate a 2x3 NumPy array with random integers between 1 and 100. Find the mean, median, and standard deviation of the array and output them.
  
```python
    import numpy as np
    random_array = np.random.randint(1, 101, size=(2, 3))
```

### Write your answer in the following code frame:

In [14]:
import numpy as np
random_array = np.random.randint(1, 101, size=(2, 3))
mean = np.mean(random_array)
median = np.median(random_array)
sd = np.std(random_array)
print(f"mean is {mean}, median is {median}, sd is {sd}")

mean is 44.666666666666664, median is 24.5, sd is 36.02622501579771


### Question 08: Concatenate the given two 1-dimensional NumPy arrays horizontally and vertically. The Numpy arrays will be generated from the following code:
  
```python
    import numpy as np
    array1 = np.array([1, 2, 3, 4])
    array2 = np.array([5, 6, 7, 8])
```

- Concatenate two arrays horizontally means that combining two or more arrays side by side along the **columns** to create a new array, and vertically means that combining them along the **row**.

### Write your answer in the following code frame:

In [21]:
import numpy as np
def combine(array1, array2):
    return np.concatenate((array1, array2))
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])
output = combine(array1, array2)
print(output)


[1 2 3 4 5 6 7 8]


### Question 09: The following code can generate a 3x3 NumPy array with random integers between 1 and 10. Replace all values greater than 5 with 8 and all values less than or equal to 5 with -3.

```python
    import numpy as np
    random_array = np.random.randint(1, 11, size=(3, 3))
```

### Write your answer in the following code frame:

In [40]:
import numpy as np
def replace(array):
    for row_index, row in enumerate(array):
        for column_index, column in enumerate(row):
            if column > 5:
                array[row_index][column_index] = 8
            else: 
                array[row_index][column_index] = -3
    return 

random_array = np.random.randint(1, 11, size=(3, 3))
print(random_array)
replace(random_array)
print(random_array)

[[ 4  5  5]
 [ 3  8 10]
 [ 3  4  6]]
[[-3 -3 -3]
 [-3  8  8]
 [-3 -3  8]]


### Question 10: Create a pandas DataFrame from the given dictionary (using the code) to store information about students, including their names, ages, and scores. Then, Calculate the average score of all students and Add a new column in the dataframe to store the grade (A, B, C, etc.) for each student based on their score.

```python
    import pandas as pd
    data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [20, 21, 19, 22],
    'Score': [83, 95, 73, 92]
    }
```

- The grading rules are: A (grade>=90), B (90>grade>=80),C (>80grade>=70), D(grade<70)

### Write your answer in the following code frame:

In [45]:
import pandas as pd
import numpy as np

def average_grade(data):
    return np.mean(data['Score'])

def grading_students(data):
    data['Grade'] = []
    for score in data['Score']:
        if score >= 90:
            data['Grade'].append('A')
        elif score >= 80:
            data['Grade'].append('B')
        elif score >= 70:
            data['Grade'].append('C')
        else:
            data['Grade'].append('D')
    return

data = {
'Name': ['Alice', 'Bob', 'Charlie', 'David'],
'Age': [20, 21, 19, 22],
'Score': [83, 95, 73, 92]
}
print(f"average score is {average_grade(data)}")
grading_students(data)
print(data['Grade'])



average score is 85.75
['B', 'A', 'C', 'A']


NameError: name 'asdf' is not defined

### Question 11: Define a function that takes a sentence as input and returns the sentence with the first letter of each word capitalized. 

- Sample sentence: Today is a sunny day.

- Expected output: Today Is A Sunny Day.

### Write your answer in the following code frame:


In [46]:
sentence = input("what is your sentence?")
print(sentence.title())

Write Your Answer In The Following Code Frame:


### Question 12 (optional): Define a class Rectangle with attributes width and height. Implement methods get_area() to calculate the area of the rectangle and get_perimeter() to calculate the perimeter. You Should use `input` function to receive the width and height values from users 


### Write your answer in the following code frame:

In [51]:
class Rectangle():
    def __init__(self, width, height):
        self.width = width
        self.height = height
    def get_area(self):
        output = self.width * self.height
        return output
    def get_perimeter(self):
        output = (self.width + self.height) *  2
        return output
width = int(input('what is the width'))
height = int(input('what is the height'))
rect = Rectangle(width, height)
print(rect.get_area())
print(rect.get_perimeter())
    

        
        

20
18
